### PR TITLE
Change retry to apply to all client requests + for HTTPError

### LINKED ISSUE #379: Spectacles should retry errors that might be transient
Semi-regularly Looker seems to return transient 4xx and 5xx errors (particularly often around git branch operations). While we do handle the exceptions gracefully, it is likely worthwhile to try those requests a few times before having the entire run fail. 

Open question as to whether this should be specific API calls or all API calls.

### PR DESCRIPTION
**Pull request by DylanBaker**
## Change description

We find that the Looker API can semi-regularly provide transient errors. We already had some logic to retry after Timeout errors. This PR extends that retry to _all_ requests and now also retries after HTTPErrors.

## Type of change
- [ ] Bug fix (fixes an issue)
- [x] New feature (adds functionality)

## Related issues

Closes #379 

### Security

- [X] Security impact of change has been considered
- [X] Code follows security best practices and guidelines

### Code review 

- [X] Pull request has a descriptive title and context useful to a reviewer

### CODE REVIEW

**Comment by joshtemple** [comment]
I wonder if it's better to take a slightly more gradual approach and only retry for 500 HTTP errors from Looker. This means we'll be unnecessarily retrying 400s and things that are our/the user's fault.

**Review by joshtemple — COMMENTED** [review]
I wonder if it's better to take a slightly more gradual approach and only retry for 500 HTTP errors from Looker. This means we'll be unnecessarily retrying 400s and things that are our/the user's fault.

**Comment by DylanBaker** [comment]
Part of the problem is that it often seems to be git related issues that are transient, which return 4XX and not 500s.

**Comment by joshtemple** [comment]
As we discussed, preference here would be to only decorate the problematic endpoints to retry 4xx responses so we don't have to worry about retries potentially delaying in situations where the error is the client's fault.

**Review by joshtemple — APPROVED** [review]

**Pull request merged**
